### ISSUE TITLE
Optimize file access and out-of-core reading 

### ISSUE THREAD

**Issue by leouieda** [fatiando/rockhound#20]
A lot of time and memory are wasted reading in whole large grids, like ETOPO1, even when only a small fraction is desired. The problem is that we store the compressed archives and need to unzip them in temporary folder every time. Since the files are temporary, we can't use xarray's lazy loading on the grids and must read them all into memory. This is not ideal.

This is a limitation of Pooch and need to think of a way of dealing with this. Ideas are welcome.

cc @santisoler

**Comment by leouieda** [comment]
fatiando/pooch#59 should allow us to do this.

**Comment by santisoler** [comment]
I agree! I think it's already solved.
