### ISSUE TITLE
LITHO1.0 model

### ISSUE THREAD

**Issue by aguspesce** [fatiando/rockhound#70]
I would like to request the LITHO1.0 model to be added to Rockhound.
This model is a 1° tessellated model of the crust and uppermost mantle of the earth, extending into the upper mantle to include the lithospheric lid and underlying asthenosphere. The model is parameterized laterally by tessellated nodes and vertically as a series of geophysically identified layers, such as water, ice, sediments, crystalline crust, lithospheric lid, and asthenosphere. 

Model/dataset name: LITHO1 (https://igppweb.ucsd.edu/~gabi/litho1.0.html)
Download link: igppweb.ucsd.edu/~gabi/litho1/litho1.0.tar.gz
License: I dont know it
Target audience: geophysicists, solid earth, etc
Is it widely used: yes

**Are you willing to help implement and maintain this feature?** Yes

**Comment by leouieda** [comment]
@aguspesce I agree, this would be great to have! Regarding the license, we should write to Gabi Laske asking her to add a CC license to these models. Both are very popular and it wouldn't hurt to put them on figshare with CC-By. I'll try to write an email explaining why we want this.

**Comment by aguspesce** [comment]
Hello @leouieda ,
It would be great if you can write the mail and ask him about the license.
Anyway, I'm going to start writing the functions to load this model because I need the model to use it in the next few weeks.

**Comment by leouieda** [comment]
:+1: sounds good!

I can copy you in the email, if you want. It might take a while for me to actually write it, though.
