### ISSUE TITLE
PREM

### ISSUE THREAD

**Issue by leouieda** [fatiando/rockhound#8]
**Description of the desired feature**

Include PREM (http://ds.iris.edu/ds/products/emc-prem/). This should be relatively straight forward as the model can be downloaded in CSV format and quickly loaded with pandas.

**Comment by leouieda** [comment]
@santis19 @aguspesce would any of you like to take a stab at this?

**Comment by santisoler** [comment]
@leouieda I can get into this.

**Comment by leouieda** [comment]
Thanks, Santi. I've assigned the issue to you.
