### ISSUE TITLE
Setup release drafter

### ISSUE THREAD

**Issue by leouieda** [fatiando/rockhound#86]
In the last [community call](https://github.com/fatiando/meeting-notes/blob/master/community-calls/2020.md#2020-07-16) we decided to roll out release drafter on RockHound to test the automated changelog generation (see fatiando/contributing#15). I setup the following [labels for this repository](https://github.com/fatiando/rockhound/labels):

![labels](https://user-images.githubusercontent.com/290082/87788677-a9741380-c835-11ea-86cb-02131f2112f2.jpg)

I would propose we configure all repos to have the same labels (with same colors) to make things easier for us. I'll open a PR to enable the Github Actions workflow for this so we can discuss other configuration options.

Are these labels OK?

**Comment by santisoler** [comment]
I think these labels are very clear!
Maybe within Rockhound we can have another one for new datasets, like `new dataset`.
Or maybe we can label PRs that add new datasets to the `feature` label.

**Comment by leouieda** [comment]
Alright, things seem to be working alright. There are few things that will still be manual when making the changelog in the docs:

1. Copy the draft release to a `changes.md` file locally
2. Convert it to rst with pandoc
3. Use `sed` to replace the `#123` PR numbers with proper links to Github (can use the same command in the current guide for Vim)
4. Replace the `@username` author list with the output from git

I would consider removing the last item and maybe leaving it as just the user names to make things simpler. Any thoughts?

**Comment by hugovk** [comment]
Labels look good! Perhaps also `removal` for what comes after `deprecation`?

**Comment by hugovk** [comment]
Looking at https://github.com/fatiando/rockhound/pull/88/files

One suggestion, add a guard to make sure release drafter doesn't run on people's own forks. 

For example: https://github.com/hugovk/pypistats/commit/e3f32234a881df4f708f211fa21852434feec187:


```yml
  update_release_draft:
    if: github.repository == 'hugovk/pypistats'
```

Also this could be omitted, because it's the default (but it's okay to be explicit too):

```yml
        with:
          # config name to use, relative to .github/
          config-name: release-drafter.yml
```

**Comment by leouieda** [comment]
> add a guard to make sure release drafter doesn't run on people's own forks. 

Ah good catch! I didn’t know actions ran on forks as well.

> Also this could be omitted, because it's the default (but it's okay to be explicit too):

I left it in there just be explicit in what that file meant. I found it confusing at first that there were two .yml files.

**Comment by leouieda** [comment]
What we need now is updated instructions for pasting the changelog in the PR. We can discuss and try them out here first and then submit to `contributing` when we roll this out to the other repositories.

Here is a draft:

* Copy the markdown from Github
* Remove the `##` from headings (optional to maintain the current style)
* Convert to rst using pandoc
* Replace the PR numbers with links (convert the vim command to `sed`?)
* Replace the authors with the `git shortlog` output

We could probably build a script that does all of this actually.
